from labwons.util import DD


FIELD_ECOS = DD(**{
	'한국은행 기준금리': DD(
		symbol='722Y001',
		code='0101000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'KORIBOR(3개월)': DD(
		symbol='817Y002',
		code='010150000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'KORIBOR(6개월)': DD(
		symbol='817Y002',
		code='010151000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'국고채1년': DD(
		symbol='817Y002',
		code='010190000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'국고채2년': DD(
		symbol='817Y002',
		code='010195000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'국고채5년': DD(
		symbol='817Y002',
		code='010200001',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'국고채10년': DD(
		symbol='817Y002',
		code='010210000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'회사채3년(AA-)': DD(
		symbol='817Y002',
		code='010300000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'회사채3년(BBB-)': DD(
		symbol='817Y002',
		code='010320000',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}%<extra></extra>',
    ),
	'은행수신금리(신규)': DD(
		symbol='121Y002',
		code='BEABAA2',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'은행수신금리(잔액)': DD(
		symbol='121Y013',
		code='BEABAB2',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'은행대출금리(신규)': DD(
		symbol='121Y006',
		code='BECBLA01',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),
	'은행대출금리(잔액)': DD(
		symbol='121Y015',
		code='BECBLB01',
		unit='%',
		category='금리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}%<extra></extra>',
    ),

	'원/달러환율': DD(
		symbol='731Y003',
		code='0000003',
		unit='원',
		category='통화/유동성지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=1,
		hover=': %{y:,.1f}원<extra></extra>',
    ),
	'M2(평잔, 원계열)': DD(
		symbol='101Y004',
		code='BBHA00',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'M2(평잔, 계절조정)': DD(
		symbol='101Y003',
		code='BBHS00',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'은행수신(말잔)': DD(
		symbol='104Y013',
		code='BCB8',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'은행수신(평잔)': DD(
		symbol='104Y014',
		code='BCA8',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'비은행수신(말잔)': DD(
		symbol='111Y007',
		code='1000000',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'비은행수신(평잔)': DD(
		symbol='111Y008',
		code='1000000',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'은행여신(말잔)': DD(
		symbol='104Y016',
		code='BDCA1',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'비은행여신(말잔)': DD(
		symbol='111Y009',
		code='1000000',
		unit='십억원',
		category='통화/유동성지표',
		YoY=True,
		MoM=True,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'증시예탁금': DD(
		symbol='901Y056',
		code='S23A',
		unit='백만원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'신용융자잔고': DD(
		symbol='901Y056',
		code='S23E',
		unit='백만원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),
	'신용대주잔고': DD(
		symbol='901Y056',
		code='S23F',
		unit='백만원',
		category='통화/유동성지표',
		YoY=True,
		MoM=False,
        dtype=int,
        digit=0,
		hover=': %{text}원<extra></extra>',
    ),

	'수출지수': DD(
		symbol='403Y001',
		code='*AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'반도체수출': DD(
		symbol='403Y001',
		code='3091AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'반도체/디스플레이장비수출': DD(
		symbol='403Y001',
		code='3091AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'스마트폰/무선전화기수출': DD(
		symbol='403Y001',
		code='309512AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'자동차수출': DD(
		symbol='403Y001',
		code='3121AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'자동차부품수출': DD(
		symbol='403Y001',
		code='31213AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'음식료품수출': DD(
		symbol='403Y001',
		code='301AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'석탄및석유제품수출': DD(
		symbol='403Y001',
		code='304AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'철강수출': DD(
		symbol='403Y001',
		code='3071AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'전지수출': DD(
		symbol='403Y001',
		code='31013AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'가전수출': DD(
		symbol='403Y001',
		code='31015AA',
		unit='',
		category='수출지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),

	'소비자물가지수': DD(
		symbol='901Y009',
		code='0',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'소비자물가지수(식료품 및 에너지 제외)': DD(
		symbol='901Y010',
		code='DB',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'소비자물가지수(서비스)': DD(
		symbol='901Y010',
		code='22',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'생산자물가지수': DD(
		symbol='404Y014',
		code='*AA',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'생산자물가지수(식료품 및 에너지 제외)': DD(
		symbol='404Y015',
		code='S620AA',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'생산자물가지수(서비스)': DD(
		symbol='404Y014',
		code='5AA',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),

	'KB부동산매매지수(아파트, 전국)': DD(
		symbol='901Y062',
		code='P63AC',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}<extra></extra>',
    ),
	'KB부동산매매지수(아파트, 서울)': DD(
		symbol='901Y062',
		code='P63ACA',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}<extra></extra>',
    ),
	'KB부동산전세지수(아파트, 전국)': DD(
		symbol='901Y063',
		code='P64AC',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}<extra></extra>',
    ),
	'KB부동산전세지수(아파트, 서울)': DD(
		symbol='901Y063',
		code='P64ACA',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=3,
		hover=': %{y:.3f}<extra></extra>',
    ),
	'아파트실거래지수(전국)': DD(
		symbol='901Y089',
		code='100',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'아파트실거래지수(서울)': DD(
		symbol='901Y089',
		code='200',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}%<extra></extra>',
    ),
	'아파트실거래지수(수도권)': DD(
		symbol='901Y089',
		code='300',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'아파트실거래지수(경기)': DD(
		symbol='901Y089',
		code='C00',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'아파트실거래지수(지방광역시)': DD(
		symbol='901Y089',
		code='M00',
		unit='',
		category='물가/부동산지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),

	'경기선행지수순환변동': DD(
		symbol='901Y067',
		code='I16E',
		unit='',
		category='경제/심리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'경기동행지수순환변동': DD(
		symbol='901Y067',
		code='I16D',
		unit='',
		category='경제/심리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'제조업업황전망': DD(
		symbol='512Y014',
		code='C0000/BA',
		unit='',
		category='경제/심리지표',
		YoY=True,
		MoM=True,
        dtype=int,
        digit=0,
		hover=': %{y:,d}<extra></extra>',
    ),
	'제조업신규수주전망': DD(
		symbol='512Y014',
		code='C0000/BD',
		unit='',
		category='경제/심리지표',
		YoY=True,
		MoM=True,
        dtype=int,
        digit=0,
		hover=': %{y:,d}<extra></extra>',
    ),
	'제조업수출전망': DD(
		symbol='512Y014',
		code='C0000/BM',
		unit='',
		category='경제/심리지표',
		YoY=True,
		MoM=True,
        dtype=int,
        digit=0,
		hover=': %{y:,d}<extra></extra>',
    ),
	'제조업심리지수': DD(
		symbol='512Y014',
		code='C0000/BY',
		unit='',
		category='경제/심리지표',
		YoY=True,
		MoM=True,
        dtype=int,
        digit=0,
		hover=': %{y:,d}<extra></extra>',
    ),
	'소비자심리지수': DD(
		symbol='511Y002',
		code='FME/99988',
		unit='',
		category='경제/심리지표',
		YoY=True,
		MoM=True,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}<extra></extra>',
    ),
	'뉴스심리지수(실험통계)': DD(
		symbol='521Y001',
		code='A001',
		unit='',
		category='경제/심리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=2,
		hover=': %{y:.2f}<extra></extra>',
    ),
	'실업률(원계열)': DD(
		symbol='901Y027',
		code='I61BC/I28A',
		unit='%',
		category='경제/심리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}%<extra></extra>',
    ),
	'실업률(계절조정)': DD(
		symbol='901Y027',
		code='I61BC/I28B',
		unit='%',
		category='경제/심리지표',
		YoY=False,
		MoM=False,
        dtype=float,
        digit=1,
		hover=': %{y:.1f}%<extra></extra>',
    ),
})

FIELD_FRED = DD(**{
    # Bond and Interest Rate
    '연준 기준금리':DD(
        symbol='FEDFUNDS',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='Federal Funds Effective Rate (Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채10년':DD(
        symbol='DGS10',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채5년':DD(
        symbol='DGS5',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채2년':DD(
        symbol='DGS2',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='Market Yield on U.S. Treasury Securities at 2-Year Constant Maturity, Quoted on an Investment Basis (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채1년':DD(
        symbol='DGS1',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='Market Yield on U.S. Treasury Securities at 1-Year Constant Maturity, Quoted on an Investment Basis (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채장단기금리차(10Y-2Y)':DD(
        symbol='T10Y2Y',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국채장단기금리차(10Y-3M)':DD(
        symbol='T10Y3M',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='10-Year Treasury Constant Maturity Minus 3-Month Treasury Constant Maturity (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 하이일드 스프레드':DD(
        symbol='BAMLH0A0HYM2',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='ICE BofA US High Yield Index Option-Adjusted Spread (Daily)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 30년고정주택담보대출':DD(
        symbol='MORTGAGE30US',
        quoteType='INDICATOR',
        category='금리지표',
        unit='%',
        comment='30-Year Fixed Rate Mortgage Average in the United States (Weekly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),

    # Monetary
    '미국 M2':DD(
        symbol='M2SL',
        quoteType='INDICATOR',
        category='통화/유동성지표',
        unit='USD(xB)',
        comment='M2: Billions of Dollars (Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}$(xB)<extra></extra>',
    ),
    '미국 M2통화유동속도':DD(
        symbol='M2V',
        quoteType='INDICATOR',
        category='통화/유동성지표',
        unit='%',
        comment='Velocity of M2 Money Stock (Seasonally Adjusted, Quarterly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),

    # Inflation
    '미국 CPI(계절조정)':DD(
        symbol='CPIAUCSL',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='',
        comment='Consumer Price Index for All Urban Consumers: All Items in U.S. City Average (Seasonally Adjusted, Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}<extra></extra>',
    ),
    '미국 CPI(계절조정 미반영)':DD(
        symbol='CPIAUCNS',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='',
        comment='Consumer Price Index for All Urban Consumers: All Items in U.S. City Average (Not Seasonally Adjusted, Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}<extra></extra>',
    ),
    '미국 CPI(경직물가, YoY)':DD(
        symbol='CORESTICKM159SFRBATL',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='%',
        comment='Sticky Price Consumer Price Index less Food and Energy (Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 CPI(식음료 에너지 제외)':DD(
        symbol='CPILFESL',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='',
        comment='Consumer Price Index for All Urban Consumers: All Items Less Food and Energy in U.S. City Average (Seasonally Adjusted, Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}<extra></extra>',
    ),
    '미국 10년 기대인플레이션율':DD(
        symbol='T10YIE',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='%',
        comment='10-Year Breakeven Inflation Rate (Daily, Not Seasonally Adjusted)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 5년 기대인플레이션율':DD(
        symbol='T5YIE',
        quoteType='INDICATOR',
        category='물가 / 부동산지표',
        unit='%',
        comment='5-Year Breakeven Inflation Rate (Daily, Not Seasonally Adjusted)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),

    # Labor, GDP, Saving and Others
    '미국 실업률':DD(
        symbol='UNRATE',
        quoteType='INDICATOR',
        category='경제 / 심리지표',
        unit='%',
        comment='Unemployment Rate(Seasonally Adjusted, Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 명목GDP':DD(
        symbol='GDP',
        quoteType='INDICATOR',
        category='경제 / 심리지표',
        unit='USD(xB)',
        comment='Gross Domestic Product (Seasonally Adjusted, Quarterly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}$(xB)<extra></extra>',
    ),
    '미국 실질GDP':DD(
        symbol='GDPC1',
        quoteType='INDICATOR',
        category='경제 / 심리지표',
        unit='USD(xB)',
        comment='Real Gross Domestic Product (Seasonally Adjusted, Quarterly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}$(xB)<extra></extra>',
    ),
    '미국 가계저축율':DD(
        symbol='PSAVERT',
        quoteType='INDICATOR',
        category='경제 / 심리지표',
        unit='%',
        comment='Personal Saving Rate (Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}%<extra></extra>',
    ),
    '미국 소비자 심리지수(미시간 대학교)':DD(
        symbol='UMCSENT',
        quoteType='INDICATOR',
        category='경제 / 심리지표',
        unit='',
        comment='University of Michigan: Consumer Sentiment (Monthly)',
        digit=2,
        dtype=float,
        hover=': %{y:.2f}<extra></extra>',
    ),
})

KRXMETA = DD(
    KOSPI=DD(
        symbol='1001',
        unit= '',
        digit=2,
        dtype=float,
        category='지수',
        hover= ': %{y:.2f}<extra></extra>',
    ),
    KOSDAQ=DD(
        symbol='2001',
        unit= '',
        digit=2,
        dtype=float,
        category='지수',
        hover= ': %{y:.2f}<extra></extra>',
    ),
)

