# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WISE INDEX
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
          python-version: '3.10'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run application
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        python "./app/taskDailyTradingDay.py"
    - name: Commits
      run: |
        git config --local user.email "jhlee_0319@naver.com"
        git config --local user.name "ACTIONS"
        git add -A
        git commit -m "WISE INDEX @ ${{ steps.ydate.outputs.ydate }}"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
